service:
  name: dynamodb-backup-scheduler

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-plugin-aws-alerts

# import custom variables
custom:
  region: ${file(./env.yml):region}
  stage: ${file(./env.yml):stage}
  backupName: ${file(./env.yml):backupName}
  backupSchedule: ${file(./env.yml):backupSchedule}
  tableNames: ${file(./env.yml):tableNames}
  retention: ${file(./env.yml):retention}
  alerts:
    stages:
      - production
    topics:
      alarm:
        topic: ${self:service}-${self:custom.stage}-alerts-alarm
        notifications: ${file(./env.yml):notifications, ''}
    alarms:
      - functionErrors
      - functionThrottles

provider:
  name: aws
  stage: ${self:custom.stage, 'dev'}
  runtime: nodejs6.10
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateBackup
        - dynamodb:ListBackups
        - dynamodb:DeleteBackup
      Resource: "*"

functions:
  backupDynamoDBTables:
    handler: handler.backupDynamoDBTables
    events:
      - schedule:
          rate: ${self:custom.backupSchedule}
          input:
            tableNames: ${self:custom.tableNames}
            retention: ${self:custom.retention}
            backupName: ${self:custom.backupName}
