service:
  name: dynamodb-backup-scheduler

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

# import custom variables
custom: ${file(./env.yml)}

provider:
  name: aws
  stage: ${self:custom.stage, 'dev'}
  runtime: nodejs6.10
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateBackup
        - dynamodb:ListBackups
        - dynamodb:DeleteBackup
      Resource: "*"

functions:
  backupDynamoDBTables:
    handler: handler.backupDynamoDBTables
    events:
      - schedule:
          rate: ${self:custom.backupSchedule}
          input:
            tableNames: ${self:custom.tableNames}
            retention: ${self:custom.retention}
            backupName: ${self:custom.backupName}
